const commands = {
    interfaceStartPause: Buffer.from('a55006', 'hex'),
    interfaceStop: Buffer.from('a55009', 'hex'),
    interfaceReset: Buffer.from('a5505a', 'hex'),
    interfaceTraceOnOff: Buffer.from('a5500f', 'hex'),
    interfaceESC: Buffer.from('a55007', 'hex'),
    interfaceLaserGate: Buffer.from('a55012', 'hex'),
    interfacePulseDown: Buffer.from('a55005', 'hex'),
    interfacePulseUp: Buffer.from('a55105', 'hex'),
    interfaceOrigin: Buffer.from('a55008', 'hex'),
    interfaceFrame: Buffer.from('a55300', 'hex'),
    interfacePlusUDown: Buffer.from('a5500c', 'hex'),
    interfacePlusUUp: Buffer.from('a5510c', 'hex'),
    interfacePlusYDown: Buffer.from('a55003', 'hex'),
    interfacePlusYUp: Buffer.from('a55103', 'hex'),
    interfacePlusZDown: Buffer.from('a5500a', 'hex'),
    interfacePlusZUp: Buffer.from('a5510a', 'hex'),
    interfaceMinusXDown: Buffer.from('a55001', 'hex'),
    interfaceMinusXUp: Buffer.from('a55101', 'hex'),
    interfaceSpeed: Buffer.from('a55011', 'hex'),
    interfacePlusXDown: Buffer.from('a55002', 'hex'),
    interfacePlusXUp: Buffer.from('a55102', 'hex'),
    interfaceMinusUDown: Buffer.from('a5500d', 'hex'),
    interfaceMinusUUp: Buffer.from('a5510d', 'hex'),
    interfaceMinusYDown: Buffer.from('a55004', 'hex'),
    interfaceMinusYUp: Buffer.from('a55104', 'hex'),
    interfaceMinusZDown: Buffer.from('a5500b', 'hex'),
    interfaceMinusZUp: Buffer.from('a5510b', 'hex'),
  };
  
  module.exports = commands;